#!/bin/bash

fping -g -r 1 20.20.8.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.9.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.10.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.11.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.12.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.13.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.14.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.15.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.16.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.17.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.18.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.19.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.20.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.21.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.22.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.23.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.24.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.25.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.26.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.27.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.28.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.29.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.30.0/25 | grep "alive" >> ip.txt
fping -g -r 1 20.20.31.0/25 | grep "alive" >> ip.txt

